# Generated by Django 5.0.6 on 2024-07-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('system', 'Sistema'), ('user', 'Candidato'), ('interviewer', 'Entrevistador')], max_length=12),
        ),
    ]
