# Generated by Django 5.0.6 on 2024-07-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_message_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'Candidato'), ('model', 'Entrevistador')], max_length=12),
        ),
    ]
